source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace='webapp')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

source/webapp/urls.py
from django.urls import path

from webapp.views import FoodListView, FoodCreateView, FoodUpdateView, FoodDeleteView, \
    OrderCreateView, OrderListView, OrderUpdateView, OrderDataUpdateView, \
    delete_view, canceled_view, delivery_view, OrderDetailView, OrderFoodAjaxCreateView, \
    OrderFoodAjaxUpdateView, OrderFoodAjaxDeleteView


from django.conf.urls.static import static
from django.conf import settings

app_name = 'webapp'

urlpatterns = [
    path('', FoodListView.as_view(), name='index'),
    path('food/create', FoodCreateView.as_view(), name='food_create'),
    path('food/<int:pk>/update', FoodUpdateView.as_view(), name='food_update'),
    path('food/<int:pk>/delete', FoodDeleteView.as_view(), name='food_delete'),


    path('order/create', OrderCreateView.as_view(), name='order_create'),
    path('orders', OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>/view', OrderDetailView.as_view(), name='order_detail'),


    path('order/<int:pk>/update_food', OrderFoodAjaxUpdateView.as_view(), name='order_ajax_update'),
    path('order/<int:pk>/data/update', OrderDataUpdateView.as_view(), name='order_data_update'),
    path('order/food/<int:pk>/delete', OrderFoodAjaxDeleteView.as_view(), name='order_delete_food'),


    path('order/<int:order_pk>/cancel', canceled_view, name='canceled_order'),
    path('order/<int:order_pk>/delivery', delivery_view, name='delivery_order'),
    path('order/<int:pk>/create_food', OrderFoodAjaxCreateView.as_view(), name='order_food_create'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='employee', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон')


class Food(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание')
    photo = models.ImageField(verbose_name='Фотография')
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return '%s %s' % (self.name, self.price)


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_PREPARING = 'preparing'
    STATUS_ON_WAY = 'on_way'
    STATUS_DELIVERED = 'delivered'
    STATUS_CANCELED = 'canceled'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый'),
        (STATUS_PREPARING, 'Готовиться'),
        (STATUS_ON_WAY, 'В пути'),
        (STATUS_DELIVERED, 'Доставлен'),
        (STATUS_CANCELED, 'Отменен')
    )

    contact_phone = models.CharField(max_length=50, verbose_name='Контактный телефон')
    contact_name = models.CharField(max_length=100, verbose_name='Имя клиента')
    delivery_address = models.CharField(max_length=200, null=True, blank=True, verbose_name='Адрес доставки')
    status = models.CharField(max_length=20, default=STATUS_NEW, verbose_name='Статус', choices=STATUS_CHOICES)
    operator = models.ForeignKey(User, blank=True, related_name='orders', verbose_name='Оператор', on_delete=models.PROTECT)
    courier = models.ForeignKey(User, null=True, blank=True, related_name='delivered', verbose_name='Курьер', on_delete=models.PROTECT)

    def __str__(self):
        return '%s %s' % (self.contact_name, self.delivery_address)


class OrderFoods(models.Model):
    order = models.ForeignKey(Order, related_name='order_foods', verbose_name='Заказ', on_delete=models.PROTECT)
    food = models.ForeignKey(Food, related_name='+', verbose_name='Блюдо', on_delete=models.PROTECT)
    amount = models.IntegerField(verbose_name='Количество')

source/webapp/forms.py
from django import forms
from webapp.models import Food, Order, OrderFoods


class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        exclude = []


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['operator']


class OrdersFoodForm(forms.ModelForm):
    class Meta:
        model = OrderFoods
        exclude = ['order']

source/webapp/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from webapp.models import Food, Order, OrderFoods
from webapp.forms import FoodForm, OrderForm, OrdersFoodForm
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.contrib.auth.models import User


class FoodListView(LoginRequiredMixin, ListView):
    template_name = 'index.html'
    model = Food


"""

redirect to login form for it we override dispatch method

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        else:
            return super().dispatch(request, *args, **kwargs)


"""


class FoodCreateView(LoginRequiredMixin, CreateView):
    model = Food
    template_name = 'create_food.html'
    form_class = FoodForm
    success_url = reverse_lazy('webapp:index')


class FoodUpdateView(LoginRequiredMixin, UpdateView):
    model = Food
    template_name = 'food_update.html'
    form_class = FoodForm
    success_url = reverse_lazy('index')


class FoodDeleteView(LoginRequiredMixin, DeleteView):
    model = Food
    template_name = 'food_delete.html'
    success_url = reverse_lazy('webapp:index')


class OrderCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Order
    template_name = 'order_create.html'
    form_class = OrderForm
    permission_required = 'webapp.add_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.operator = self.request.user
        return super().form_valid(form)

#Order Food create view with page reloading
class OrderCreateFoodView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = OrderFoods
    template_name = 'order_food_create.html'
    form_class = OrdersFoodForm
    permission_required = 'webapp.add_orderfoods'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = Order.objects.get(pk=self.kwargs.get('pk'))
        return context

    def form_valid(self, form):
        form.instance.order = get_object_or_404(Order, pk=self.kwargs['pk'])
        return super().form_valid(form)


#Order Food create view with AJAX
class OrderFoodAjaxCreateView(CreateView, FormView):
    model = OrderFoods
    form_class = OrdersFoodForm
    permission_required = 'webapp.add_orderfoods'

    def form_valid(self, form):
        order = get_object_or_404(Order, pk=self.kwargs.get('pk'))
        form.instance.order = order
        order_food = form.save()
        return JsonResponse({
            'food_name': order_food.food.name,
            'food_pk': order_food.food.pk,
            'amount': order_food.amount,
            'pk': order_food.pk,
            'edit_url': reverse('webapp:order_ajax_update', kwargs={'pk': order_food.pk}),
            'delete_url': reverse('webapp:order_delete_food', kwargs={'pk': order_food.pk})
        })

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status='422')




#Order Food update view with AJAX
class OrderFoodAjaxUpdateView(UpdateView, FormView):
    model = OrderFoods
    form_class = OrdersFoodForm
    permission_required = 'webapp.change_orderfoods'

    def form_valid(self, form):
        order_food = form.save()
        return JsonResponse({
            'food_name': order_food.food.name,
            'food_pk': order_food.food.pk,
            'amount': order_food.amount,
            'pk': order_food.pk
        })

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors
        }, status=422)



#Order Food update view with reloading
class OrderUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = OrderFoods
    template_name = 'order_update.html'
    form_class = OrdersFoodForm
    permission_required = 'webapp.change_orderfoods'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.order.pk})


class OrderDataUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Order
    template_name = 'order_data_update.html'
    form_class = OrderForm
    permission_required = 'webapp.change_order'

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': self.object.pk})


class OrderDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView, FormView):
    model = Order
    template_name = 'order_view.html'
    form_class = OrdersFoodForm
    permission_required = 'webapp.view_order'


class OrderListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = 'order_list.html'
    model = Order
    permission_required = 'webapp.view_order'


def delete_view(request, food_pk):
    foods = get_object_or_404(OrderFoods, pk=food_pk)
    foods.delete()
    return redirect('webapp:order_list')




class OrderFoodAjaxDeleteView(LoginRequiredMixin, DeleteView):
    model = OrderFoods

    def delete(self, request, *args, **kwargs):
        delete_food = get_object_or_404(OrderFoods, pk=self.kwargs.get('pk'))
        pk = delete_food.pk
        delete_food.delete()
        return JsonResponse({
            'pk': pk
        })

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:order_detail', kwargs={'pk': get_object_or_404(OrderFoods, pk=self.kwargs.get('pk')).order.pk})




def canceled_view(request, order_pk):
    orders = get_object_or_404(Order, pk=order_pk)
    if orders:
        orders.status = 'canceled'
        orders.save()
        return redirect('webapp:order_list')


def delivery_view(request, order_pk):
    orders = get_object_or_404(Order, pk=order_pk)
    orders.courier = request.user
    if orders.status == 'preparing':
        orders.status = 'on_way'
        orders.save()
        return redirect('webapp:order_list')
    elif orders.status == 'on_way':
        orders.status = 'delivered'
        orders.save()
        return redirect('webapp:order_list')

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
            <li class="nav-item navbar-text">Привет {{ request.user.username }}</li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'webapp:index' %}" class="nav-link">На главную</a>
            </li>
            {% block menu %}{% endblock %}
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Вход</a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/create_food.html
{% extends 'base.html' %}
{% block title %}Добавить блюдо{% endblock %}
{% block content %}
    <h2>Добавить блюдо: </h2>
     <form action="{% url 'webapp:food_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
           <p>{{ field.label_tag }}</p> <p>{{ field }}</p><br>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
{% endblock %}

source/webapp/templates/food_delete.html
{% extends 'base.html' %}
{% block title %}Удалить блюдо{% endblock %}
{% block content %}
    <h4>Вы уверены что хотите удалить блюдо {{ food.name }}?</h4>
    <form action="{% url 'webapp:food_delete' food.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/food_update.html
{% extends 'base.html' %}
{% block title %}Изменить блюдо{% endblock %}
{% block content %}
    <h2>Изменить блюдо: {{ food.name }} </h2>
     <form action="{% url 'webapp:food_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
           <p>{{ field.label_tag }}</p> <p>{{ field }}</p><br>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block title %}Блюда{% endblock %}
{% block menu %}
    <li class="nav_item"><a href="{% url 'webapp:food_create' %}" class="nav-link">Добавить блюдо</a></li>
    <li class="nav_item"><a href="{% url 'webapp:order_list' %}" class="nav-link">Список заказов</a></li>
    {% if perms.webapp.add_order %}
        <li class="nav_item"><a href="{% url 'webapp:order_create' %}" class="nav-link">Создать заказ</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    {% for food in food_list %}
        <div class="card-group mx-auto col-md-6 text-center m-3">
            <div class="card">
                <img class="card-img-top" src="{{ food.photo.url }}" alt="Картинка с блюдом">
                <div class="card-body">
                    <h5 class="card-title">{{ food.name }} - {{ food.price }} сом</h5>
                    <p class="card-text">{{ food.description }}</p>
                    <p class="card-text"><a href="{% url 'webapp:food_update' food.pk %}">Изменить блюдо</a></p>
                    <p class="card-text"><a href="{% url 'webapp:food_delete' food.pk %}">Удалить блюдо</a></p>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

source/webapp/templates/order_create.html
{% extends 'base.html' %}
{% block title %}Заказ{% endblock %}
{% block content %}
    <h2 class="text-center">Стол заказов</h2>
     <form action="{% url 'webapp:order_create' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
           <p>{{ field.label_tag }}</p> <p>{{ field }}</p><br>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
{% endblock %}

source/webapp/templates/order_data_update.html
{% extends 'base.html' %}
{% block title %}Изменить данные заказ{% endblock %}
{% block menu %}
     <li class="nav-item">
         <a href="{% url 'webapp:order_list' %}" class="nav-link">Список заказов</a>
     </li>
{% endblock %}
{% block content %}
    <h2 class="text-center">Изменить данные заказа {{ order.contact_name }}</h2>
     <form action="{% url 'webapp:order_data_update' order.pk %}" method="post">
        {% csrf_token %}
        {% for field in form %}
           <p>{{ field.label_tag }}</p> <p>{{ field }}</p><br>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
{% endblock %}

source/webapp/templates/order_food_create.html
{% extends 'base.html' %}
{% block title %}Заказ{% endblock %}
{% block content %}
    <h2 class="text-center">Сделать заказ</h2>
     <form action="{% url 'webapp:order_food_create' order.pk %}" method="post">
        {% csrf_token %}
        {% for field in form %}
           <p>{{ field.label_tag }}</p> <p>{{ field }}</p><br>
        {% endfor %}
        <div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </form>
{% endblock %}

source/webapp/templates/order_list.html
{% extends 'base.html' %}
{% block title %}Заказы{% endblock %}
{% block menu %}
    <li class="nav_item"><a href="{% url 'webapp:order_create' %}" class="nav-link">Создать заказ</a></li>
{% endblock %}
{% block content %}
    <h2>Список заказов: </h2>
    {% for order in order_list %}
        <div class="list-group">
             <a class="list-group-item list-group-item-action" href="{% url 'webapp:order_detail' order.pk %}">{{ order.contact_name }} {{ order.delivery_address }}</a>
        </div>
    {% endfor %}
{% endblock %}

source/webapp/templates/order_update.html
{% extends 'base.html' %}
{% block title %}Изменить заказ{% endblock %}
{% block menu %}
     <li class="nav-item">
         <a href="{% url 'webapp:order_list' %}" class="nav-link">Список заказов</a>
     </li>
{% endblock %}
{% block content %}
    <h2 class="text-center">Изменить заказ {{ orderfoods.order.contact_name }}</h2>
        <form action="{% url 'webapp:order_update' orderfoods.pk %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <p>{{ field.label_tag }}</p> <p>{{ field }}</p><br>
            {% endfor %}
            <div>
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>



{% endblock %}

source/webapp/templates/order_view.html
{% extends 'base.html' %}
{% block title %}Заказы{% endblock %}
{% block menu %}
    <li class="nav_item"><a href="{% url 'webapp:order_create' %}" class="nav-link">Создать заказ</a></li>
    <li class="nav_item"><a href="{% url 'webapp:order_list' %}" class="nav-link">Список заказов</a></li>
{% endblock %}
{% block content %}
    <ul class="list-group mt-2">
        {% if order.status == 'delivered' %}
            <li class="list-group-item m-2">
                Заказ {{ order.contact_name }} {{ order.delivery_address }} доставляется или доставлен
            </li>
        {% else %}
            <li class="list-group-item_1"><p>Имя заказчика: {{ order.contact_name }}</p>
                <p>Адрес заказчика: {{ order.delivery_address }}</p>
                <p>Статус: {{ order.get_status_display }}</p>

                 <!-- working block of code --->
                <ul id="order_food_list">
                    {% for food in order.order_foods.all %}
                        <li id="order_food_{{ food.pk }}" class="list-group-item"> <!-- add pk for li --->
                            <span id="order_food_name_{{ food.pk }}" data-food_pk="{{ food.food.pk }}">{{ food.food.name }}</span>:
                            <span id="order_food_amount_{{ food.pk }}">{{ food.amount }}</span> <span>шт</span>
                            {% if perms.webapp.change_orderfoods %}
                                <a class="edit_link" data-pk="{{ food.pk }}" href="{% url 'webapp:order_ajax_update' food.pk %}">Изменить блюдо</a> /
                                <a class="delete_link" data-pk="{{ food.food.pk }}" href="{% url 'webapp:order_delete_food' food.pk %}">Удалить блюдо</a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>


                {% if perms.webapp.delete_order %}
                    <p><a href="{% url 'webapp:canceled_order' order.pk %}">Отменить заказ</a></p>
                {% endif %}
                {% if perms.webapp.add_orderfoods %}
                    <a href="{% url 'webapp:order_food_create' order.pk %}" id="order_food_add_link">Добавить блюдо</a><br>
                {% endif %}
                {% if perms.webapp.change_order %}
                    <p class="text-right"><a href="{% url 'webapp:order_data_update' order.pk %}">Изменить данные
                        заказа</a></p>
                {% endif %}
                {% if order.status == 'preparing' and perms.webapp.view_food %}
                    <p><a href="{% url 'webapp:delivery_order' order.pk %}">Взять заказ</a></p>
                {% elif order.status == 'on_way' and perms.webapp.view_food and order.courier == request.user %}
                    <p><a href="{% url 'webapp:delivery_order' order.pk %}">Доставить заказ</a></p>
                {% endif %}
            </li>
        {% endif %}
    </ul>

    <div class="modal" tabindex="-1" role="dialog" id="modal_for_food">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Добавить блюдо</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="food_form" action="{% url 'webapp:order_food_create' order.pk %}" method="post">
                        <div class="text-danger"  id="food_form_errors"></div>
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary" id="food_submit">Добавить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript">

        //Successfully ajax func processing
        function onCreateSuccess(response, status) {
            console.log(response);
            console.log(status);

            let foodNameSpan = $('<span></span>')
                .attr('id', 'order_food_name_' + response.pk)
                .data('food_pk', response.food_pk)
                .text(response.food_name);
            let foodAmountSpan = $('<span></span>')
                .attr('id', 'order_food_amount_' + response.pk)
                .text(response.amount);


            let editLink = $('<a></a>').addClass('edit_link')
                .attr('href', response.edit_url)
                .data('pk', response.pk)
                .text('Изменить блюдо')
                .click(onOrderFoodUpdate);

            let deleteLink = $('<a></a>')
                .attr('href', response.delete_url)
                .data('pk', response.pk)
                .text('Удалить блюдо')
                .click(onOrderFoodDelete)
                .addClass('delete_link');


            let newFoodLi = $('<li></li>').addClass('list-group-item')
                .attr('id', 'order_food_' + response.pk)
                .append(foodNameSpan)
                .append(document.createTextNode(': '))
                .append(foodAmountSpan)
                .append(document.createTextNode(' шт. '))
                .append(editLink)
                .append(document.createTextNode(' / '))
                .append(deleteLink);



            $('#order_food_list').append(newFoodLi);
            $('#modal_for_food').modal('hide');

        }
        // Processing Ajax on update food
        function onUpdateSuccess(response, status) {
            console.log(response);
            console.log(status);

            let pk = response['pk'];
            let foodNameSpan = $('#order_food_name_' + pk);
            foodNameSpan.text(response.food_name);
            foodNameSpan.data('food_pk', response.food_pk);
            $('#order_food_amount_' + pk).text(response['amount']);

            $('#modal_for_food').modal('hide');
        }

        //Ajax func processing with error
        function onFormSubmitError(response, status) {
            console.log(response);
            console.log(status);


        }

        //Sending Ajax response with form
        function orderFoodFormSubmit(success) {
            // get url to form sending
            let url = $('#food_form').attr('action');
            // collect data from food_form
            let data = {
                food: $('#id_food').val(),
                amount: $('#id_amount').val(),
                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()

            };

            $.ajax({
                url: url,
                method: 'POST',
                data: data,
                success: success,
                error: onFormSubmitError
            });
        }

        function onOrderFoodCreate(event) {
            event.preventDefault();
            $("#modal_for_food .modal-title").text('Добавить блюдо');
            $("#food_submit").text('Добавить');

            let foodForm = $('#food_form');
            foodForm.attr('action', $(this).attr('href'));

            $('#id_food').val('');
            $('#id_amount').val('');

            foodForm.off('submit');

            foodForm.on('submit', function (event) {
                event.preventDefault();
                orderFoodFormSubmit(onCreateSuccess);
            });

            $('#modal_for_food').modal('show');

        }



        function onOrderFoodUpdate(event) {
            event.preventDefault();

            $("#modal_for_food .modal-title").text('Изменить блюдо');
            $('#food_submit').text('Изменить');

            let foodForm = $('#food_form');
            foodForm.attr('action', $(this).attr('href'));

            let foodPk = $(this).data('pk');
            let foodName = $('#order_food_name_' + foodPk);
            let foodAmount = $("#order_food_amount_" + foodPk);
            $("#id_food").val(foodName.data('food_pk'));
            $('#id_amount').val(foodAmount.text());

            foodForm.off('submit');

            foodForm.submit(function (event) {
                event.preventDefault();

                orderFoodFormSubmit(onUpdateSuccess);
                
            });

            $('#modal_for_food').modal('show');

        }
// delete function
        function onOrderFoodDelete(event) {
            event.preventDefault();
            let url = $(this).attr('href');

            $.ajax ({
                url: url,
                success: onDeleteFoodSuccess,
                error: onFormSubmitError,
                method: 'GET'
            })

        }

        function onDeleteFoodSuccess(response, status) {
            console.log(response);
            console.log(status);

            let pk = response['pk'];
            let foodLi = $('#order_food_' + pk);
            foodLi.remove();

        }

//
        $(function () {
            $("#food_submit").on('click', function () {
                $('#food_form').submit();

            });
            $('#order_food_add_link').click(onOrderFoodCreate);

            $('#order_food_list .edit_link').click(onOrderFoodUpdate);

            $('#order_food_list .delete_link').click(onOrderFoodDelete);

        })




    </script>
{% endblock %}